blueprint:
  name: Day Night Light
  description: Toggle a light based on the position of the sun.
  domain: automation
  source_url: https://github.com/Sander0542/home-assistant-blueprints/blob/main/automations/day_night_light.yaml
  input:
    sunrise_offset:
      name: Sunrise Offset
      default: 0
      selector:
        text: {}
    sunset_offset:
      name: Sunset Offset
      default: 0
      selector:
        text: {}
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
mode: restart
max_exceeded: silent
trigger:
- platform: sun
  event: sunrise
  offset: !input 'sunrise_offset'
- platform: sun
  event: sunset
  offset: !input 'sunset_offset'
action:
- variables:
    service: '{% if trigger.event == ''sunrise'' %}light.turn_off{% else %}light.turn_on{%endif %}'
- service: '{{ service }}'
  target: !input 'light_target'
