blueprint:
  name: Day Night Switch
  description: Toggle a switch based on the position of the sun.
  domain: automation
  source_url: https://github.com/Sander0542/home-assistant-blueprints/blob/main/automations/day_light_switch.yaml
  input:
    sunrise_offset:
      name: Sunrise Offset
      default: 0
      selector:
        text:
    sunset_offset:
      name: Sunset Offset
      default: 0
      selector:
        text:
    switch_target:
      name: Switch
      selector:
        target:
          entity:
            domain: switch

mode: restart
max_exceeded: silent

trigger:
  - platform: sun
    event: sunrise
    offset: !input 'sunrise_offset'
  - platform: sun
    event: sunset
    offset: !input 'sunset_offset'

action:
  - variables:
      service: >-
        {% if trigger.event == 'sunrise' %}switch.turn_off{% else %}switch.turn_on{% endif %}
  - service: '{{ service }}'
    target: !input 'switch_target'
