blueprint:
  name: Sun Elevation Lights
  description: Toggle lights based on the elevation of the sun.
  domain: automation
  source_url: https://github.com/Sander0542/home-assistant-blueprints/blob/main/automations/sun_elevation_lights.yaml
  input:
    elevation:
      name: Elevation
      default: 0
      selector:
        number:
          min: -90
          max: 90
          step: 0.01
          unit_of_measurement: '°'
    light_target:
      name: Lights
      selector:
        target:
          entity:
            domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    id: dawn
    above: !input 'elevation'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    id: dusk
    below: !input 'elevation'

action:
  - if:
      - condition: trigger
        id: dawn
    then:
      - service: light.turn_off
        target: !input 'light_target'
    else:
      - service: light.turn_on
        target: !input 'light_target'
