blueprint:
  name: Television Light
  description: Turn off a light when the television starts playing.
  domain: automation
  source_url: https://github.com/Sander0542/home-assistant-blueprints/blob/main/automations/tv_light.yaml
  input:
    television_target:
      name: Television
      selector:
        entity:
          domain: media_player
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input television_target
  to: "playing"

action:
  - service: light.turn_off
    target: !input light_target
